### ISSUE TITLE
Corrigir Tencologias

### ISSUE THREAD

**Issue by FelypeGanzert** [DeveloperArthur/euarthur#1]
Você pode editar o seu arquivo style.css da parte de tecnologias para o seguinte: (está tudo comentado)

`
#tecnologias {
    /* um espaço de 20px acima e abaixo, o auto e pra direita e equerda 
       dessa forma a div fica centralizada */
    margin: 20px auto;
    padding: 15px; /*Espaço interno */
    max-width: 600px; /* Tamanho máximo da div */
}

#tecnologias ul{
    display: grid; /* para a organização em 'colunas' */
    gap: 20px; /* Espaço entre cada tecnologia */
    grid-template-columns: 1fr 1fr 1fr; /* Define que terá 3 colunas */
}

/* Para colocar a linha abaixo da última tecnologia */
#tecnologias ul li.list-group-item:last-child {
    border-width: 0 0 1px; 
}

/* Media query para ficar show no mobile */
@media(max-width: 600px){
    #tecnologias ul{
        grid-template-columns: 1fr 1fr; /* Exibe só duas colunas no lugar de 3 */
    }
}
`

**Comment by DeveloperArthur** [comment]
Obrigado !!!
